### ISSUE TITLE
Autosync Subscribers from another DB

### ISSUE THREAD

**Issue by hareluya86** [SegMail/SegMail#110]
A batch job can be submitted that reads a table from another DB on a regular basis to add/update subscription info.

**Comment by hareluya86** [comment]
There are 2 ways of implementing this:

1) Direct integration: 
- Create a datasource module that directly reads the data at runtime via HTTP/HTTPS calls, MySQL protocol calls, etc.
- Store a runtime mapping of fields between Segmail and the datasource.
- Enhance all ListService, SubscriptionService, MailmergeService methods to switch datasources during runtime.

**Pros**
- More accurate and up-to-date

**Cons**
- Much harder to implement
- Datasource might become a bottleneck for Segmail UI

2) Periodic Synchronization:
- Create an EJB that can be scheduled to call all datasource at an interval.
- Create an EnterpriseData<SubscriptionList> that stores the datasource, the time of last sync, the interval required.
- Create an EnterpriseData<SubscriptionList> that stores the field mapping.

**Pros**
- Easier to implement
- Faster and less latency when users use Segmail UI

**Cons**
- Might have runtime issues that are undetected eg. New subscribers not synced.

**Comment by hareluya86** [comment]
There is a problem with date field types.
java.sql.SQLException: Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp

	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998)

	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:937)

	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)

	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:872)

	at com.mysql.jdbc.ResultSetImpl.getTimestampFromString(ResultSetImpl.java:5699)

	at com.mysql.jdbc.ResultSetImpl.getStringInternal(ResultSetImpl.java:5338)

	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5167)

	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5206)

	at segmail.component.subscription.datasource.DatasourceQueryService.getRemoteSubscribers(DatasourceQueryService.java:119)

**Comment by hareluya86** [comment]
Issue with unsubscribing random emails. Root cause is the wrong initialization of the email field.
