### ISSUE TITLE
Scheduled Campaign executions keep failing

### ISSUE THREAD

**Issue by hareluya86** [SegMail/SegMail#119]
After a campaign is executed, an EJB error is thrown and the entire application's EJB timer stopped. Before this happens, there seem to be SQL insert statements into EMAIL table, but no records are found. Likely cause was that the number of records to be committed is overloading the entire application's memory and caused an irrecoverable error.

The immediate solution would be to reduce the number of records per flush in CampaignExecutionService. However, there is another subtle problem at the batch processing level - our design of batch processing seems to be consuming too much memory and transactions are not created in the proper manner. We have not given enough thought to this as we rushed to go live, but it seems that batch processing is not mature enough to be used in a live production system. 

In light of that, we can either:
1) Keep using batch processing and go back to the drawing board to re-design, re-develop and re-test it.
2) Skip batch processing totally and create hardcoded cron methods in each EJB service for each specific use. Eg. one in MailInboundService and MailOutboundService that runs separately on their own.

So action items:
1) Decide if batch processing is to be used with Segmail
2) Optimize CampaignExecutionService.

**Comment by hareluya86** [comment]
Could it be causes by this:
1) Cron thread runs. 
2) Cron thread starts batch execution EJB (same thread)
3) Batch execution EJB encounters write exception and throws it upwards. 
4) Cron thread catches the exception, throws it, and stops.

**Comment by hareluya86** [comment]
After removing JPA lock in executeCampaign(), we encountered transaction timeout transaction "EJB5123:Rolling back timed out transaction".

To ensure a robust system, we will need to handle batch job executions in a different way so that it is not affected by a transaction timeout, regardless of the timeout duration. The EJB transactions have to be carefully designed such that:
1) Each batch job run has their own transaction scope - any exception thrown within its own execution will be contained and reported properly without disrupting the EJBTimer's scope.
2) The running time of each batch job run will not affect the Cron thread execution or its transactions. 

Detailed stack trace:
javax.ejb.EJBTransactionRolledbackException
	at com.sun.ejb.containers.BaseContainer.mapLocal3xException(BaseContainer.java:2342)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2123)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2044)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
	at com.sun.proxy.$Proxy443.getEm(Unknown Source)
	at eds.component.__EJB31_Generated__UpdateObjectService__Intf____Bean__.getEm(Unknown Source)
	at eds.component.batch.BatchProcessingService.processBatchJobQueue(BatchProcessingService.java:93)
	at eds.component.batch.BatchProcessingService.cron(BatchProcessingService.java:188)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:73)
	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.GeneratedMethodAccessor129.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundTimeout(SystemInterceptorProxy.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
	at com.sun.ejb.containers.BaseContainer.callEJBTimeout(BaseContainer.java:4051)
	at com.sun.ejb.containers.EJBTimerService.deliverTimeout(EJBTimerService.java:1199)
	at com.sun.ejb.containers.EJBTimerService.access$000(EJBTimerService.java:89)
	at com.sun.ejb.containers.EJBTimerService$TaskExpiredWork.run(EJBTimerService.java:1919)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.ejb.TransactionRolledbackLocalException: Client's transaction aborted
	at com.sun.ejb.containers.EJBContainerTransactionManager.useClientTx(EJBContainerTransactionManager.java:361)
	at com.sun.ejb.containers.EJBContainerTransactionManager.preInvokeTx(EJBContainerTransactionManager.java:255)
	at com.sun.ejb.containers.BaseContainer.preInvokeTx(BaseContainer.java:4524)
	at com.sun.ejb.containers.BaseContainer.preInvoke(BaseContainer.java:1986)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:210)
	... 43 more

**Comment by hareluya86** [comment]
Another issue is that when the batch job starts, the status is not reflected in the DB. Probably it is in a different transaction scope.

**Comment by hareluya86** [comment]
Even though it is a REQUIRES_NEW transaction scope, as long as it is invoking the same class, it will use the same transaction.
http://stackoverflow.com/questions/22348539/when-exactly-does-jpa-requires-new-transaction-commit#comment33967863_22348577
More explanation: https://stackoverflow.com/a/427582

**Comment by hareluya86** [comment]
After adding transaction attributes to a few child methods and eliminating flush(), we are left with a more hopeful stack trace  telling us where the rollback exception was thrown, but we still don't know why they were thrown:

javax.ejb.EJBTransactionRolledbackException
	at com.sun.ejb.containers.BaseContainer.mapLocal3xException(BaseContainer.java:2342)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2123)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2044)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
	at com.sun.proxy.$Proxy346.getEm(Unknown Source)
	at eds.component.__EJB31_Generated__GenericObjectService__Intf____Bean__.getEm(Unknown Source)
	at segmail.component.campaign.CampaignExecutionService.getUnsubscribeCodes(CampaignExecutionService.java:320)
	at segmail.component.campaign.CampaignExecutionService.executeCampaignActivity(CampaignExecutionService.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
---cut short---

**Comment by hareluya86** [comment]
When do we need TransactionAttribute?
- If there is no DB operation, don’t put it.
- If there is only a DB read, put REQUIRED
- If there is a DB write, put REQUIRED or REQUIRED_NEW

REQUIRED_NEW:
- Only works if you are calling a separate EJB. If you call the same method within the client EJB annotated with REQUIRED_NEW, it will still regard it as the same transaction.

Solution:
- Call a separate helper service method annotated with REQUIRED_NEW.
- Call this helper method in batches (eg. 500)
- For batch execution, update the status of the batch job run using the same method.

However, after this change, we are still getting "java.lang.OutOfMemoryError: GC overhead limit exceeded" exception and the whole Glassfish stops responding. If batch job error reporting is working though, then this won't be a problem because the BatchExecutionService would log this as an error.

**Comment by hareluya86** [comment]
Sometimes REQUIRED will cause transaction rollback problems, probably because (I suspect) all objects that are retrieved in that call will be associated with that session. It seems that REQUIRES_NEW works better but since it is only a read operation, NOT_SUPPORTED would be more suitable. 

Therefore, if an EJB has a method that requires transaction context, all of its methods should also require transaction context. If an EJB calls its own methods, they should be of the same transaction context because it would be called within the same transaction context anyway regardless if you put REQUIRES_NEW.

**Comment by hareluya86** [comment]
Closed in capterra-1 branch
