### ISSUE TITLE
Campaign cannot be created

### ISSUE THREAD

**Issue by hareluya86** [SegMail/SegMail#135]
When creating a new campaign and checking if the existing Client has a sending address and contact info, retrieving these 2 EnterpriseData object has caused a WrongClassException in Hibernate.

Exception info:

Caused by: org.hibernate.WrongClassException: Object [id=eds.entity.data.EnterpriseData_$$_jvst822_1@525535504] was not of the specified subclass [eds.entity.client.ContactInfo] : loaded object was of wrong class class eds.entity.client.VerifiedSendingAddress
	at org.hibernate.loader.Loader.instanceAlreadyLoaded(Loader.java:1581)
	at org.hibernate.loader.Loader.getRow(Loader.java:1532)
	at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:727)
	at org.hibernate.loader.Loader.processResultSet(Loader.java:972)
	at org.hibernate.loader.Loader.doQuery(Loader.java:930)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:336)
	at org.hibernate.loader.Loader.doList(Loader.java:2611)
	at org.hibernate.loader.Loader.doList(Loader.java:2594)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2423)
	at org.hibernate.loader.Loader.list(Loader.java:2418)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:501)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:371)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:220)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1268)
	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:87)
	at org.hibernate.jpa.internal.QueryImpl.list(QueryImpl.java:567)
	at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:436)
	... 163 more
]]

**Comment by hareluya86** [comment]
Root cause: both ContactInfo and VerifiedSendingAddress have the same primary key. This cause hibernate to think that they are the same object in memory.

**Comment by hareluya86** [comment]
Fixed the problem in EDS https://github.com/SegMail/EDS/commit/16aa44ebb9dc72dfffd73e877ac15ddfe82b9b5c

**Comment by hareluya86** [comment]
Other than code fix, we will need to either:
1) Refresh the entire database
2) Update each table one by one and add in the DATA_TYPE columns

There are currently 12 ED classes. Since we already have production data, then let's just do 2) by introducing a DB Patch.

**Comment by hareluya86** [comment]
To get all EnterpriseData table name:
```
SELECT A.NAME
FROM
	(SELECT TABLE_NAME as NAME, COUNT(TABLE_NAME) as C
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE COLUMN_NAME IN ('OWNER','START_DATE','END_DATE','SNO')
        AND TABLE_SCHEMA='segmail'
	GROUP BY TABLE_NAME) A
WHERE 
	C >= 4
```

**Comment by hareluya86** [comment]
Fixed by MySQL scripts, which will be committed into code base
