### ISSUE TITLE
Batch job monitoring screen hangs when certain statuses are selected/unselected

### ISSUE THREAD

**Issue by hareluya86** [SegMail/SegMail#142]
Caused by: java.lang.NullPointerException
	at seca2.program.batch.FormJobList.getRunTime(FormJobList.java:163)

**Comment by hareluya86** [comment]
In addition to the /batch screen error above, there is a 

1) Performance issue, and

2) Runtime issue:
Caused by: java.lang.NullPointerException
	at eds.entity.batch.BatchJobRunError.<init>(BatchJobRunError.java:44)
	at eds.entity.batch.BatchJobContainerHelper.logErrors(BatchJobContainerHelper.java:59)
