### ISSUE TITLE
Parameter value [NEWSLETTER] did not match expected type [org.hibernate.type.EnumType (n/a)]

### ISSUE THREAD

**Issue by hareluya86** [SegMail/SegMail#32]
EnumType.STRING is not recognized as a valid type in 5.0.0.Final. It threw the exception: 
Caused by: java.lang.IllegalArgumentException: Parameter value [NEWSLETTER] did not match expected type [org.hibernate.type.EnumType (n/a)]
    at org.hibernate.jpa.spi.BaseQueryImpl.validateBinding(BaseQueryImpl.java:858)
    at org.hibernate.jpa.internal.QueryImpl.access$000(QueryImpl.java:62)
    at org.hibernate.jpa.internal.QueryImpl$ParameterRegistrationImpl.bindValue(QueryImpl.java:235)
    at org.hibernate.jpa.spi.BaseQueryImpl.setParameter(BaseQueryImpl.java:603)
    at org.hibernate.jpa.spi.AbstractQueryImpl.setParameter(AbstractQueryImpl.java:163)
    at org.hibernate.jpa.spi.AbstractQueryImpl.setParameter(AbstractQueryImpl.java:32)
    at org.hibernate.jpa.criteria.compile.CriteriaCompiler$1$1.bind(CriteriaCompiler.java:109)
    at org.hibernate.jpa.criteria.CriteriaQueryImpl$1.buildCompiledQuery(CriteriaQueryImpl.java:369)
    at org.hibernate.jpa.criteria.compile.CriteriaCompiler.compile(CriteriaCompiler.java:130)
    at org.hibernate.jpa.spi.AbstractEntityManagerImpl.createQuery(AbstractEntityManagerImpl.java:699)
    at com.sun.enterprise.container.common.impl.EntityManagerWrapper.createQuery(EntityManagerWrapper.java:500)
    at segmail.component.subscription.SubscriptionService.getAvailableTemplatesForClient(SubscriptionService.java:334)
    ... 142 more

**Comment by hareluya86** [comment]
Could be the solution:
http://stackoverflow.com/a/27964437

**Comment by hareluya86** [comment]
Resolved by not using an enum anymore until Hibernate 5 stabilizes.
