### ISSUE TITLE
Some columns are read from the wrong tables in a multi-level heirarchy table

### ISSUE THREAD

**Issue by hareluya86** [SegMail/SegMail#35]
Given the entities:

```
ConfirmationEmailTemplate extends EmailTemplate
EmailTemplate extends EnterpriseObject
```

The following exception is thrown when GenericObjectService.getEnterpriseObjectById(objectid, EmailTemplate.class) is called:

```
Caused by: com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Unknown column 'emailtempl0_.OBJECT_TYPE' in 'field list'
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
    at com.mysql.jdbc.Connection.execSQL(Connection.java:3283)
    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1332)
    at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1467)
    at com.sun.gjc.spi.jdbc40.PreparedStatementWrapper40.executeQuery(PreparedStatementWrapper40.java:642)
    at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:70)
    ... 121 more
```

**Comment by hareluya86** [comment]
Not a showstopper, easily resolved by retrieving an EnterpriseObject instead and casting it to EmailTemplate.

**Comment by hareluya86** [comment]
This issue was solved somehow solved by https://github.com/SegMail/EDS/commit/02ad466341f72b794b01576abdbd07b53fde5012
