### ISSUE TITLE
Hibernate ID generator cannot be casted from 4.3.6 onwards

### ISSUE THREAD

**Issue by hareluya86** [SegMail/SegMail#7]
org.hibernate.id.MultipleHiLoPerTableGenerator cannot be cast to org.hibernate.id.IdentifierGenerator
at org.hibernate.id.factory.internal.DefaultIdentifierGeneratorFactory.createIdentifierGenerator(DefaultIdentifierGeneratorFactory.java:115)

The exception occurs when first deploying the app. The hibernate engine is trying to get the ID generator for our EnterpriseObject class, which is declared as a Table strategy. 

Happens to all version from Hibernate 4.3.6 onwards. The casting works fine in 4.3.5.

**Comment by hareluya86** [comment]
Raised our first bug on https://hibernate.atlassian.net/browse/HHH-10047 !

**Comment by hareluya86** [comment]
After our issue has been classified as a duplicate of https://hibernate.atlassian.net/browse/HHH-9446, a bit of reading leads us to check the stack trace for the classloader that was used. Turns out that the stacktrace was still showing 4.3.6 codes instead of 4.3.9 codes, particularly at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.withTccl(ClassLoaderServiceImpl.java:398) where our Netbeans IDE is displaying the codes from the new fix but clearly it is executing the old codes.

Severe:   Exception while preparing the app : [PersistenceUnit: HIBERNATE] Unable to build Hibernate SessionFactory
org.hibernate.MappingException: Could not instantiate id generator [entity-name=eds.entity.data.EnterpriseObject]
    at org.hibernate.id.factory.internal.DefaultIdentifierGeneratorFactory.createIdentifierGenerator(DefaultIdentifierGeneratorFactory.java:123)
    at org.hibernate.mapping.SimpleValue.createIdentifierGenerator(SimpleValue.java:213)
    at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:323)
    at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1857)
    at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:850)
    at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:843)
    at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.withTccl(ClassLoaderServiceImpl.java:398)

**Comment by hareluya86** [comment]
According to Gail Badner, issue was fixed by introducing a new variable hibernate.classloading.use_current_tccl_as_parent which is set to true by default but it's running into some errors in GF. Only when set to false then it will exhibit pre-4.3.6 behaviour.

https://hibernate.atlassian.net/browse/HHH-9446?focusedCommentId=67147&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-67147

Let's do this first.
